version: '3'

services:
  php7:
    build:
      context: .
      dockerfile: docker/php7/Dockerfile
    ports:
      - "7074:80"
    volumes:
      - ./app:/var/www/html
    environment:
      - PHP_ENV=development
    networks:
      - php-migration-net

  php8:
    build:
      context: .
      dockerfile: docker/php8/Dockerfile
    ports:
      - "8082:80"
    volumes:
      - ./app:/var/www/html
    environment:
      - PHP_ENV=development
    networks:
      - php-migration-net

networks:
  php-migration-net:
    driver: bridge
